config/routes.rb
Rails.application.routes.draw do
  resources :projets
  resources :departements
  resources :employes

  root "employes#index"

end

app/models/departement.rb
class Departement < ActiveRecord::Base
  validates_presence_of :nom
  validates_uniqueness_of :nom
  has_many :employes
end

app/models/employe.rb
class Employe < ActiveRecord::Base
  validates_presence_of :nom, :prenom
  validates_uniqueness_of :nom, :prenom
  belongs_to :departement

end

app/models/projet.rb
class Projet < ActiveRecord::Base
  belongs_to :employe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departements_controller.rb
class DepartementsController < ApplicationController
  before_action :set_departement, only: [:show, :edit, :update, :destroy]

  # GET /departements
  # GET /departements.json
  def index
    @departements = Departement.all
  end

  # GET /departements/1
  # GET /departements/1.json
  def show
  end

  # GET /departements/new
  def new
    @departement = Departement.new
  end

  # GET /departements/1/edit
  def edit
  end

  # POST /departements
  # POST /departements.json
  def create
    @departement = Departement.new(departement_params)

    respond_to do |format|
      if @departement.save
        format.html { redirect_to @departement, notice: 'Departement was successfully created.' }
        format.json { render :show, status: :created, location: @departement }
      else
        format.html { render :new }
        format.json { render json: @departement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departements/1
  # PATCH/PUT /departements/1.json
  def update
    respond_to do |format|
      if @departement.update(departement_params)
        format.html { redirect_to @departement, notice: 'Departement was successfully updated.' }
        format.json { render :show, status: :ok, location: @departement }
      else
        format.html { render :edit }
        format.json { render json: @departement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departements/1
  # DELETE /departements/1.json
  def destroy
    @departement.destroy
    respond_to do |format|
      format.html { redirect_to departements_url, notice: 'Departement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departement
      @departement = Departement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departement_params
      params.require(:departement).permit(:nom, :budget, :ville)
    end
end

app/controllers/employes_controller.rb
class EmployesController < ApplicationController
  before_action :set_employe, only: [:show, :edit, :update, :destroy]

  # GET /employes
  # GET /employes.json
  def index
    @employes = Employe.all
  end

  # GET /employes/1
  # GET /employes/1.json
  def show
  end

  # GET /employes/new
  def new
    @employe = Employe.new
  end

  # GET /employes/1/edit
  def edit
  end

  # POST /employes
  # POST /employes.json
  def create
    @employe = Employe.new(employe_params)

    respond_to do |format|
      if @employe.save
        format.html { redirect_to @employe, notice: 'Employe was successfully created.' }
        format.json { render :show, status: :created, location: @employe }
      else
        format.html { render :new }
        format.json { render json: @employe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employes/1
  # PATCH/PUT /employes/1.json
  def update
    respond_to do |format|
      if @employe.update(employe_params)
        format.html { redirect_to @employe, notice: 'Employe was successfully updated.' }
        format.json { render :show, status: :ok, location: @employe }
      else
        format.html { render :edit }
        format.json { render json: @employe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employes/1
  # DELETE /employes/1.json
  def destroy
    @employe.destroy
    respond_to do |format|
      format.html { redirect_to employes_url, notice: 'Employe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employe
      @employe = Employe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employe_params
      params.require(:employe).permit(:nom, :prenom, :salaire)
    end
end

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController
  before_action :set_projet, only: [:show, :edit, :update, :destroy]

  # GET /projets
  # GET /projets.json
  def index
    @projets = Projet.all
  end

  # GET /projets/1
  # GET /projets/1.json
  def show
  end

  # GET /projets/new
  def new
    @projet = Projet.new
  end

  # GET /projets/1/edit
  def edit
  end

  # POST /projets
  # POST /projets.json
  def create
    @projet = Projet.new(projet_params)

    respond_to do |format|
      if @projet.save
        format.html { redirect_to @projet, notice: 'Projet was successfully created.' }
        format.json { render :show, status: :created, location: @projet }
      else
        format.html { render :new }
        format.json { render json: @projet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projets/1
  # PATCH/PUT /projets/1.json
  def update
    respond_to do |format|
      if @projet.update(projet_params)
        format.html { redirect_to @projet, notice: 'Projet was successfully updated.' }
        format.json { render :show, status: :ok, location: @projet }
      else
        format.html { render :edit }
        format.json { render json: @projet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projets/1
  # DELETE /projets/1.json
  def destroy
    @projet.destroy
    respond_to do |format|
      format.html { redirect_to projets_url, notice: 'Projet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projet
      @projet = Projet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projet_params
      params.require(:projet).permit(:nom, :budget)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departements_helper.rb
module DepartementsHelper
end

app/helpers/employes_helper.rb
module EmployesHelper
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/views/departements/_form.html.erb
<%= form_for(@departement) do |f| %>
  <% if @departement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@departement.errors.count, "error") %> prohibited this departement from being saved:</h2>

      <ul>
      <% @departement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :budget %><br>
    <%= f.text_field :budget %>
  </div>
  <div class="field">
    <%= f.label :ville %><br>
    <%= f.text_area :ville %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departements/edit.html.erb
<h1>Editing Departement</h1>

<%= render 'form' %>

<%= link_to 'Show', @departement %> |
<%= link_to 'Back', departements_path %>

app/views/departements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Departements</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Budget</th>
      <th>Ville</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departements.each do |departement| %>
      <tr>
        <td><%= departement.nom %></td>
        <td><%= departement.budget %></td>
        <td><%= departement.ville %></td>
        <td><%= link_to 'Show', departement %></td>
        <td><%= link_to 'Edit', edit_departement_path(departement) %></td>
        <td><%= link_to 'Destroy', departement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departement', new_departement_path %>

app/views/departements/new.html.erb
<h1>New Departement</h1>

<%= render 'form' %>

<%= link_to 'Back', departements_path %>

app/views/departements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @departement.nom %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @departement.budget %>
</p>

<p>
  <strong>Ville:</strong>
  <%= @departement.ville %>
</p>

<%= link_to 'Edit', edit_departement_path(@departement) %> |
<%= link_to 'Back', departements_path %>

app/views/employes/_form.html.erb
<%= form_for(@employe) do |f| %>
  <% if @employe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employe.errors.count, "error") %> prohibited this employe from being saved:</h2>

      <ul>
      <% @employe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :prenom %><br>
    <%= f.text_field :prenom %>
  </div>
  <div class="field">
    <%= f.label :salaire %><br>
    <%= f.text_field :salaire %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employes/edit.html.erb
<h1>Editing Employe</h1>

<%= render 'form' %>

<%= link_to 'Show', @employe %> |
<%= link_to 'Back', employes_path %>

app/views/employes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employes</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Salaire</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employes.each do |employe| %>
      <tr>
        <td><%= employe.nom %></td>
        <td><%= employe.prenom %></td>
        <td><%= employe.salaire %></td>
        <td><%= link_to 'Show', employe %></td>
        <td><%= link_to 'Edit', edit_employe_path(employe) %></td>
        <td><%= link_to 'Destroy', employe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employe', new_employe_path %>

app/views/employes/new.html.erb
<h1>New Employe</h1>

<%= render 'form' %>

<%= link_to 'Back', employes_path %>

app/views/employes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @employe.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @employe.prenom %>
</p>

<p>
  <strong>Salaire:</strong>
  <%= @employe.salaire %>
</p>

<%= link_to 'Edit', edit_employe_path(@employe) %> |
<%= link_to 'Back', employes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Employes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projets/_form.html.erb
<%= form_for(@projet) do |f| %>
  <% if @projet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projet.errors.count, "error") %> prohibited this projet from being saved:</h2>

      <ul>
      <% @projet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :budget %><br>
    <%= f.text_field :budget %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projets/edit.html.erb
<h1>Editing Projet</h1>

<%= render 'form' %>

<%= link_to 'Show', @projet %> |
<%= link_to 'Back', projets_path %>

app/views/projets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projets</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Budget</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projets.each do |projet| %>
      <tr>
        <td><%= projet.nom %></td>
        <td><%= projet.budget %></td>
        <td><%= link_to 'Show', projet %></td>
        <td><%= link_to 'Edit', edit_projet_path(projet) %></td>
        <td><%= link_to 'Destroy', projet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Projet', new_projet_path %>

app/views/projets/new.html.erb
<h1>New Projet</h1>

<%= render 'form' %>

<%= link_to 'Back', projets_path %>

app/views/projets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @projet.nom %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @projet.budget %>
</p>

<%= link_to 'Edit', edit_projet_path(@projet) %> |
<%= link_to 'Back', projets_path %>